### ISSUE TITLE
examples/documentation?

### ISSUE THREAD

**Issue by mqklin** [gsklee/react-chartist-tooltip#1]
Hi, can you provide some examples/docs?
Thanks!

**Comment by burgerzzz** [comment]
Yes, would love to have even a basic example.

**Comment by rosven** [comment]
Would be awesome with some documentation for this plugin. 
Thank you.

**Comment by ellenschwartau** [comment]
Did anyone find out how it's working? Example would be really really helpful. 
Thank you!

**Comment by gsklee** [comment]
Sorry but there's no such plan since I no longer use it. However, **the [source code](https://github.com/gsklee/react-chartist-tooltip/blob/master/react-chartist-tooltip.babel.js) is really simple** so please just go look at it and figure it out.

**Comment by djkantoci** [comment]
It would be sooo cool if example is provided, since we wouldn't need this code if we already knew how to use it :)
